#!/usr/bin/env python3
"""Curate contemporary Chinese cocktail copy without changing canonical English facts."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RECIPES_PATH = ROOT / "data" / "recipes.json"
NAMES_PATH = ROOT / "data" / "name-zh.json"
INSTRUCTIONS_PATH = ROOT / "data" / "instruction-zh.json"


NAME_OVERRIDES = {
    "747 Drink": "747 特调",
    "Affair": "绯闻",
    "Americano": "阿美利卡诺",
    "Aviation": "航空",
    "Boston Sour": "波士顿酸",
    "Brain Fart": "脑袋宕机",
    "Darkwood Sling": "暗木司令",
    "Drinking Chocolate": "热巧克力",
    "Duchamp's Punch": "杜尚潘趣",
    "English Highball": "英式高球",
    "Fruit Cooler": "水果酷乐",
    "Gin Cooler": "金酒酷乐",
    "Gin Lemon": "金酒柠檬",
    "Gin Sling": "金酒司令",
    "Gin Smash": "金酒史玛希",
    "Gin Squirt": "金酒 Squirt",
    "Gin Swizzle": "金酒斯威泽",
    "Gin Toddy": "金酒托迪",
    "Halloween Punch": "万圣节潘趣",
    "Holloween Punch": "万圣节潘趣",
    "Japanese Fizz": "日式菲士",
    "Jello shots": "果冻 shot",
    "Kool-Aid Shot": "Kool-Aid shot",
    "Lemon Elderflower Spritzer": "柠檬接骨木花斯普里泽",
    "Lemon Shot": "柠檬 shot",
    "Lone Tree Cooler": "孤树酷乐",
    "Mudslinger": "Mudslinger",
    "Orange Crush": "橙味 Crush",
    "Pornstar Martini": "艳星马天尼",
    "Pink Gin": "粉红金酒",
    "Raspberry Cooler": "覆盆子酷乐",
    "Royal Gin Fizz": "皇家金酒菲士",
    "Rum Cooler": "朗姆酷乐",
    "Spritz": "斯普里兹",
    "Tequila Fizz": "龙舌兰菲士",
    "Vodka Fizz": "伏特加菲士",
    "Wine Cooler": "葡萄酒酷乐",
    "Yoghurt Cooler": "酸奶酷乐",
}

# Cocktail names are proper nouns. Use established mainland bar names where
# they exist; otherwise prefer a readable transliteration or retain the source
# name instead of inventing a literal Chinese title.
NAME_OVERRIDES.update({
    "151 Florida Bushwacker": "151 佛罗里达布什瓦克",
    "24k nightmare": "24K 噩梦",
    "3 Wise Men": "三贤者",
    "3-Mile Long Island Iced Tea": "三英里长岛冰茶",
    "410 Gone": "410 Gone",
    "501 Blue": "501 蓝",
    "57 Chevy with a White License Plate": "白牌 57 雪佛兰",
    "69 Special": "69 特调",
    "9 1/2 Weeks": "九周半",
    "Applecar": "Applecar",
    "Baby Eskimo": "Baby Eskimo",
    "B-52": "B-52 轰炸机",
    "Bible Belt": "圣经地带",
    "Big Red": "Big Red",
    "Broadside": "舷侧炮",
    "Bora Bora": "波拉波拉",
    "Cafe Savoy": "萨沃伊咖啡",
    "Caipirinha": "卡皮里尼亚",
    "Caipirissima": "卡皮里西玛",
    "Casino": "卡西诺",
    "City Slicker": "都市客",
    "Coke and Drops": "可乐加柠檬滴",
    "Corpse Reviver": "亡者复苏",
    "Damned if you do": "Damned if you do",
    "Dark Caipirinha": "深色卡皮里尼亚",
    "Dirty Nipple": "Dirty Nipple",
    "Diesel": "Diesel",
    "Downshift": "Downshift",
    "Egg Cream": "纽约蛋奶汽水",
    "Elderflower Caipirinha": "接骨木花卡皮里尼亚",
    "Empellón Cocina's Fat-Washed Mezcal": "Empellón Cocina 脂洗梅斯卡尔",
    "English Rose Cocktail": "英伦玫瑰",
    "Espresso Rumtini": "浓缩咖啡朗姆蒂尼",
    "Foxy Lady": "狐媚佳人",
    "French 75": "法式 75",
    "French Negroni": "法式内格罗尼",
    "Fruit Flip-Flop": "Fruit Flip-Flop",
    "Frappé": "Frappé 冰咖啡",
    "Fuzzy Asshole": "Fuzzy Asshole",
    "Gin Daisy": "金酒黛西",
    "Gin Sour": "金酒酸",
    "Grasshopper": "青草蜢",
    "Harvey Wallbanger": "哈维撞墙",
    "Ice Pick": "冰锥",
    "Irish Russian": "爱尔兰俄罗斯",
    "Jelly Bean": "软糖豆",
    "Just a Moonmint": "Just a Moonmint",
    "Kentucky B And B": "肯塔基 B&B",
    "Kill the cold Smoothie": "驱寒冰沙",
    "Kiwi Lemon": "猕猴桃柠檬",
    "Kiwi Martini": "猕猴桃马天尼",
    "Kiwi Papaya Smoothie": "猕猴桃木瓜冰沙",
    "Kool First Aid": "Kool-Aid 急救",
    "Kool-Aid Slammer": "Kool-Aid Slammer",
    "Lassi - A South Indian Drink": "南印度拉西",
    "Lassi - Mango": "芒果拉西",
    "Lassi - Sweet": "甜味拉西",
    "Lassi Khara": "咸味拉西",
    "Lassi Raita": "拉西莱塔",
    "Lazy Coconut Paloma": "懒人椰香帕洛玛",
    "Limeade": "青柠饮",
    "Long vodka": "长饮伏特加",
    "Michelada": "米切拉达",
    "Mint Julep": "薄荷朱莉普",
    "Monkey Wrench": "Monkey Wrench",
    "New York Lemonade": "纽约柠檬特饮",
    "Nuked Hot Chocolate": "微波热巧克力",
    "Nutty Irishman": "榛果爱尔兰人",
    "Old Pal": "老友",
    "Orange Oasis": "橙香绿洲",
    "Orange Push-up": "Orange Push-up",
    "Orange Whip": "橙香 Whip",
    "Pink Penocha": "Pink Penocha",
    "Pegu Club": "佩谷俱乐部",
    "Popped cherry": "Popped Cherry",
    "Port And Starboard": "左舷右舷",
    "Port Wine Flip": "波特酒 Flip",
    "Porto flip": "波尔图 Flip",
    "Pysch Vitamin Light": "Pysch Vitamin Light",
    "Pure Passion": "Pure Passion",
    "Quaker's Cocktail": "贵格会鸡尾酒",
    "Quick F**K": "Quick F**K",
    "Rail Splitter": "Rail Splitter",
    "Raspberry Julep": "覆盆子朱莉普",
    "Royal Bitch": "Royal Bitch",
    "Rum Cobbler": "朗姆柯布勒",
    "Rum Runner": "Rum Runner",
    "Rum Old-fashioned": "朗姆古典",
    "Sherry Flip": "雪莉 Flip",
    "Shot-gun": "Shot-gun",
    "Smut": "Smut",
    "Sol Y Sombra": "日与影",
    "Stone Sour": "Stone Sour",
    "Sweet Tooth": "嗜甜",
    "Tequila Surprise": "龙舌兰惊喜",
    "Thriller": "Thriller",
    "Tequila Slammer": "龙舌兰炸弹",
    "Tomato Tang": "番茄 Tang",
    "Vermouth Cassis": "味美思黑加仑",
    "Vodka Slime": "Vodka Slime",
    "Waikiki Beachcomber": "Waikiki Beachcomber",
    "Whitecap Margarita": "白浪玛格丽特",
    "Winter Rita": "冬日丽塔",
    "Winter Paloma": "冬日帕洛玛",
    "Zenmeister": "Zenmeister",
    "Zizi Coin-coin": "Zizi Coin-coin",
    "Corn n Oil": "Corn ’n Oil",
    "Flander's Flake-Out": "Flander's Flake-Out",
    "Frosé": "Frosé 桃红酒冰沙",
    "Hot Chocolate to Die for": "要命热巧克力",
    "Irish Curdling Cow": "Irish Curdling Cow",
    "Lunch Box": "Lunch Box",
    "Orangeade": "橙汁汽水",
    "Pink Panty Pulldowns": "Pink Panty Pulldowns",
    "Quarter Deck Cocktail": "后甲板鸡尾酒",
    "The Galah": "粉红凤头鹦鹉",
    "The Last Word": "遗言",
    "Tia-Maria": "添万利咖啡利口酒",
    "Wine Punch": "葡萄酒潘趣",
    "Ziemes Martini Apfelsaft": "Ziemes Martini Apfelsaft",
    "Zimadori Zinger": "Zimadori Zinger",
    "Zinger": "Zinger",
    "Zipperhead": "Zipperhead",
    "Zippy's Revenge": "Zippy's Revenge",
})


ENGLISH_TEMPLATES = {
    "Shake all ingredients with ice, strain into a cocktail glass, and serve.": "所有材料加冰摇匀，滤入鸡尾酒杯。",
    "Shake ingredients with ice, strain into a cocktail glass, and serve.": "材料加冰摇匀，滤入鸡尾酒杯。",
    "Stir all ingredients with ice, strain into a cocktail glass, and serve.": "所有材料加冰搅拌，滤入鸡尾酒杯。",
    "Stir ingredients with ice, strain into a cocktail glass, and serve.": "材料加冰搅拌，滤入鸡尾酒杯。",
    "Shake all ingredients with ice, strain into a chilled cocktail glass, and serve.": "所有材料加冰摇匀，滤入冰镇鸡尾酒杯。",
    "Shake all ingredients (except carbonated water) with ice and strain into a highball glass over two ice cubes. Fill with carbonated water, stir, and serve.": "除气泡水外，所有材料加冰摇匀，滤入装有两块冰的高球杯；以气泡水补满并轻轻搅匀。",
    "Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up.": "所有材料倒入搅拌机，以中速打至顺滑；可分装为 1 大杯、2 中杯或 3 小杯。",
    "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a cocktail glass.": "摇酒壶加冰至半满，倒入所有材料充分摇匀，滤入鸡尾酒杯。",
    "In a shaker half-filled with ice cubes, combine all of the ingredients. Shake well. Strain into a sour glass.": "摇酒壶加冰至半满，倒入所有材料充分摇匀，滤入酸酒杯。",
    "In a mixing glass half-filled with ice cubes, combine all of the ingredients. Stir well. Strain into a cocktail glass.": "调酒杯加冰至半满，倒入所有材料搅匀，滤入鸡尾酒杯。",
    "Pour all ingredients directly into old fashioned glass filled with ice cubes. Stir gently.": "将所有材料直接倒入装有冰块的古典杯，轻轻搅匀。",
    "Throw everything into a blender and liquify.": "所有材料倒入搅拌机，打至顺滑。",
    "Mix together and enjoy!": "将所有材料混合均匀。",
    "Mix together and enjoy": "将所有材料混合均匀。",
    "Mix. Serve over ice.": "混合均匀，加冰饮用。",
    "Layered in a shot glass.": "将材料依次分层倒入 shot 杯。",
    "Pour ingredients into 1 ounce shot glass": "将材料倒入 1 oz shot 杯。",
    "Stir in mixing glass with ice and strain": "材料倒入调酒杯加冰搅拌，滤入成品杯。",
    "Shake and strain into a chilled cocktail glass": "加冰摇匀，滤入冰镇鸡尾酒杯。",
}


INSTRUCTION_OVERRIDES = {
    "110 in the shade": "将装有龙舌兰酒的 shot 杯沉入啤酒杯，再以拉格啤酒加满。",
    "151 Florida Bushwacker": "所有材料倒入搅拌机，打至顺滑；按需饰以巧克力屑。",
    "155 Belmont": "所有材料加冰搅打，倒入白葡萄酒杯，饰以胡萝卜。",
    "24k nightmare": "所有材料加冰摇匀，滤入 shot 杯。",
    "252": "将两种酒倒入 shot 杯，一口饮下。",
    "3 Wise Men": "将三种威士忌倒入杯中混合，以 shot 方式一口饮下。",
    "3-Mile Long Island Iced Tea": "在 14 oz 杯中加满冰，再加入各款烈酒；倒入可乐至杯子的三分之二，以酸甜预调液补满。最后滴入少量苦精，饰以柠檬角。",
    "50/50": "杯中加入碎冰，依次倒入伏特加和少量金万利橙酒，最后以橙汁加满。",
    "501 Blue": "杯中加冰，倒入等量的两种材料并混合均匀。",
    "57 Chevy with a White License Plate": "古典杯加满冰，加入白可可利口酒和伏特加，搅匀。",
    "69 Special": "杯中加入 2 oz 金酒、4 oz 七喜与少量柠檬汁；按口味以更多七喜补满。",
    "747 Drink": "柯林杯加满冰，依次倒入伏特加、青柠果露和蔓越莓汁，再以雪碧补满。饰以青柠片或蔓越莓。",
    "747": "依次倒入 Kahlúa、百利甜酒和 Frangelico 榛果利口酒；不冰镇，也不做分层。",
    "9 1/2 Weeks": "所有材料倒入调酒杯加冰搅拌至冰镇，滤入鸡尾酒杯，饰以草莓片。",
    "A1": "所有材料与冰倒入摇酒壶，摇匀后连冰倒入冰镇杯。",
    "ACID": "先倒入 151 proof 朗姆酒，再加入 Wild Turkey 101；另配可乐或胡椒博士汽水作为 chaser。",
    "Addington": "两款味美思加冰摇匀，滤入冰镇杯，再补少量苏打水。",
    "Acapulco": "除薄荷外，将所有材料加冰摇匀，滤入装有冰块的古典杯，饰以一枝薄荷。",
    "Affair": "高球杯加冰，依次加入施纳普斯、橙汁和蔓越莓汁，以苏打水补满。",
    "Alexander": "所有材料加冰摇匀，滤入鸡尾酒杯，撒少量肉豆蔻。",
    "Algonquin": "所有材料加冰摇匀，滤入鸡尾酒杯。",
    "Allegheny": "除柠檬皮外，所有材料加冰摇匀并滤入鸡尾酒杯，饰以柠檬皮卷。",
    "Americano": "古典杯加冰，倒入金巴利和甜味美思，加入少量苏打水，饰以半片橙子。",
    "Aviation": "所有材料倒入摇酒壶加冰摇匀，滤入鸡尾酒杯，饰以樱桃。",
    "Avalon": "高球杯加满冰，依次加入芬兰伏特加、柠檬汁、苹果汁和 Pisang Ambon 香蕉利口酒，以柠檬汽水补满。轻轻搅拌，饰以螺旋黄瓜皮与红樱桃。黄瓜带来清新气息，也让装饰更醒目。这杯酒由 Timo Haimi 创作，曾获 1991 年 Finlandia Vodka Long Drink Competition 冠军。",
    "B-52": "按顺序将材料分层倒入 shot 杯，配搅拌棒。",
    "B-53": "依次将 Kahlúa、Sambuca 和 Grand Marnier 分层倒入 shot 杯。",
    "Baby Eskimo": "冰淇淋在室温下放约 10 分钟，再按顺序加入其余材料，用筷子、餐刀或勺子搅匀后立即饮用。口感轻盈，适合接在酒体较厚重的饮品之后。",
    "Bahama Mama": "所有材料混合，按口味加入约 2 份苏打水，倒入装有大量冰块的杯中，配吸管。",
    "Barracuda": "除起泡酒外，所有材料加冰摇匀并滤入杯中，再以起泡酒补满。",
    "Bob Marley": "将材料倒入 2 oz shot 杯。",
    "Bumble Bee": "百利甜酒先倒入 shot 杯。将吧勺背面贴近杯壁，沿吧勺依次缓慢倒入 Kahlúa 和 Sambuca，使三层保持分明。",
    "Caipirinha": "将青柠块与糖放入古典杯，用捣棒或木勺压出汁液与精油。加满冰后倒入卡莎萨。",
    "Corn n Oil": "将半个青柠再切成两块，连同法勒南和苦精放入古典杯捣压。加入陈年朗姆酒和冰，搅匀；最后将黑糖蜜朗姆酒漂浮在酒面，配吸管。",
    "Cranberry Punch": "混合前四种材料并搅至糖完全溶解，冷藏。上桌前加入姜汁汽水，再放入冰环保持低温。",
    "Clover Club": "所有材料先不加冰干摇至蛋清乳化，再加冰摇匀，双重滤入鸡尾酒杯。",
    "Corpse Reviver": "以苦艾酒润洗鸡尾酒杯。其余材料加冰摇匀，双重滤入杯中。",
    "Cuba Libra": "高球杯加满冰，加入朗姆酒。用青柠切面擦拭杯口后将汁挤入杯中，以可口可乐补满，饰以青柠片。",
    "Darkwood Sling": "杯中加入一份樱桃利口酒和一份苏打水。若想做成偏酸版本，可加入汤力水；再加入冰块并以橙汁补满。",
    "Duchamp's Punch": "所有材料加冰摇匀，双重过滤至装有一块大冰的冰镇双份古典杯，饰以两枝薰衣草。",
    "Death in the Afternoon": "苦艾酒倒入冰镇杯，再以香槟补满。",
    "Empellón Cocina's Fat-Washed Mezcal": "先制作阿多波腌料：将安乔辣椒、瓜希略辣椒、墨西哥烟熏辣椒、烤蒜、苹果醋、墨西哥牛至、黑胡椒、丁香、肉桂和孜然打成细腻酱汁。按原配方将猪肋排冷熏、腌制并低温烤熟，冷却后收集猪油；也可用猪油加少量腌料加热替代。\n\n将等量梅斯卡尔和调味猪油倒入密封容器，充分摇匀后冷冻一夜。待油脂凝固分层，以细网筛过滤，再用纱布或咖啡滤纸滤净残余油脂。\n\n哈瓦那辣椒酊：辣椒切片后加入 2 oz 梅斯卡尔，浸泡一夜或至所需辣度。\n\n调酒：梅斯卡尔与巧克力利口酒在调酒杯中加冰搅拌 45 秒，滤入冰镇碟形香槟杯。借助吧勺沿杯壁缓慢沉入咖啡利口酒，最后滴入 5 滴辣椒酊。",
    "Figgy Thyme": "用刘易斯冰袋将冰块敲碎，倒入柯林杯。摇酒壶中放入无花果和百里香捣压，再加入蜂蜜伏特加、柠檬汁与一块大冰，摇至充分冰镇后滤入杯中。加入汤力水和 2 dash 安格仕芳香苦精，饰以无花果片与百里香。",
    "French Negroni": "将所有材料与冰倒入摇酒壶，用吧勺搅拌 40–45 圈，或至充分冰镇。滤入马天尼杯，亦可滤入装有冰块的古典杯；饰以橙皮卷。",
    "Gimlet": "所有材料倒入摇酒壶并加满冰，摇匀后滤入冰镇鸡尾酒杯；也可滤入装有新冰的古典杯。饰以青柠片。",
    "Gin Cooler": "在柯林杯中搅匀糖粉和 2 oz 气泡水，加满冰后倒入金酒，再以气泡水补满并搅匀。加入柠檬皮和螺旋橙皮，让橙皮一端垂在杯沿外。",
    "Gin Lemon": "高球杯加满冰，倒入金酒并以柠檬汽水补满，轻轻搅匀，饰以柠檬片；也可加几片薄荷叶。",
    "Gin Swizzle": "摇酒壶加冰至半满，倒入青柠汁、糖、金酒和苦精并摇匀。冰镇杯加满冰，将酒液滤入，再以苏打水补满；搅拌至杯壁挂霜。",
    "Halloween Punch": "将葡萄汁和苏打水、姜汁汽水或柠檬青柠汽水倒入潘趣碗混合。舀入橙味与青柠味雪葩，让表面稍微融化，同时保留完整的雪葩球。",
    "Holloween Punch": "将葡萄汁和苏打水、姜汁汽水或柠檬青柠汽水倒入潘趣碗混合。舀入橙味与青柠味雪葩，让表面稍微融化，同时保留完整的雪葩球。",
    "Jello shots": "将 3 杯水煮沸，加入果冻粉并搅至完全溶解。倒入 2 杯伏特加混匀，分装进塑料 shot 杯，冷藏至凝固后食用。",
    "Kool First Aid": "将 Kool-Aid 倒入双份 shot 杯，以朗姆酒补满，一口饮下。",
    "Lemon Shot": "将加利安奴与绝对伏特加柠檬味倒入 shot 杯混合，把撒糖的柠檬角放在杯口，沿柠檬淋少量朗姆酒。仅由专业调酒师点燃约 1 秒并彻底熄灭后，一口饮下并咬一口柠檬。",
    "Long vodka": "用冰块和安格仕芳香苦精摇洗高杯内壁，倒入伏特加。加入一片青柠，再挤入其余青柠汁，以汤力水补满并搅匀。",
    "Penicillin": "将调和苏格兰威士忌、柠檬汁、蜂蜜糖浆和姜糖浆加冰摇匀，滤入装有大冰块的冰镇古典杯。将烟熏型苏格兰威士忌漂浮在酒面，饰以糖渍姜。",
    "Pegu Club": "所有材料加冰摇匀，双重滤入鸡尾酒杯。",
    "Red Snapper": "每款材料各取 1 shot，加冰摇匀后滤入 shot 杯，一口饮下。",
    "Snowday": "所有材料加冰搅拌，滤入装有新冰的冰镇古典杯。挤压橙皮释放精油，并以橙皮装饰。",
    "Spritz": "杯中加冰，依次倒入材料，完成装饰。",
    "Stinger": "所有材料倒入调酒杯加冰搅拌，滤入鸡尾酒杯；也可滤入装有冰块的古典杯。",
    "Vampiro": "可使用高球杯或古典杯。先以青柠汁或水润湿杯口，蘸一圈犹太盐。杯中加冰至半满，倒入 1–2 shot 优质龙舌兰酒；挤入新鲜青柠汁，加入少量盐与柑橘汽水至约八分满，再加入 Viuda de Sanchez，或以橙汁、青柠汁和墨西哥辣酱替代。最后搅匀。",
    "Vodka Tonic": "切一角和一片青柠或柠檬。杯中加满新冰，倒入伏特加，再以汤力水补满。将果角挤汁入杯，饰以果片。",
    "Wine Cooler": "葡萄酒与柠檬青柠汽水混合，倒入杯中并加冰。",
    "Yoghurt Cooler": "酸奶和水果放入搅拌机，以中速打至顺滑。倒入 1 个大杯、2 个中杯或 3 个小杯。炎热天气可多加冰：搅拌机运转时从投料口逐次加入 3–4 块冰，打至完全碎化。",
    "Zinger": "shot 杯中倒入 4 shot 桃味施纳普斯，再加入 4 shot Surge 汽水，一口饮下。",
    "Zipperhead": "杯中加满冰，先放入吸管，再依次加入材料并尽量保持分层：香博覆盆子利口酒在底层，伏特加居中，苏打水在上层。",
    "Zoksel": "没有特别的调法：将所有材料依次倒入同一只杯中，配柠檬。",
}

# These records contained literal machine translation, mistranslated brand
# names, or wording that does not belong behind a contemporary Chinese bar.
# Each override is translated back from the canonical English record above it;
# quantities and preparation facts are deliberately left unchanged.
INSTRUCTION_OVERRIDES.update({
    "Abilene": "高球杯加满冰，直接倒入所有材料，搅匀。",
    "Apello": "所有材料与大量冰块充分搅匀，饰以樱桃。",
    "AT&T": "古典杯加冰，依次倒入伏特加和金酒，再以汤力水补满并搅匀。",
    "Avalanche": "所有材料加冰混合并充分摇匀，倒入高球杯。",
    "Bellini": "将桃泥倒入冰镇笛形香槟杯，加入普罗塞克起泡酒，轻轻搅匀。",
    "Bible Belt": "所有材料混合后倒在冰块上。",
    "Blackthorn": "黑刺李金酒和味美思加冰搅拌，滤入鸡尾酒杯；饰以柠檬皮卷。",
    "Boomerang": "金酒、干味美思、苦精和马拉斯奇诺利口酒倒入半杯冰的调酒杯，搅匀后滤入鸡尾酒杯；饰以马拉斯奇诺樱桃。",
    "Bora Bora": "所有材料加冰摇匀，滤入高球杯；饰以菠萝片和樱桃。也可将材料加冰打至顺滑后装杯。",
    "Boston Sour": "威士忌、柠檬汁、糖粉和蛋清加碎冰摇匀，滤入酸酒杯；饰以柠檬片和樱桃。",
    "Brain Fart": "所有材料缓慢、轻柔地混合。潘趣碗中加冰，并确保汽水充分冰镇，效果更佳。",
    "Broadside": "杯中加冰至半满，将苦艾草压碎后放在冰上，再倒入 151 proof 朗姆酒、苏格兰威士忌和苦精。",
    "Buccaneer": "将科罗娜啤酒倒入啤酒杯，再加入一 shot 白朗姆酒。",
    "Cafe Savoy": "杯中先倒入热咖啡至近满，再加入牛奶、白橙皮利口酒和白兰地，搅匀。",
    "Caipirissima": "做法与卡皮里尼亚相同，但以白朗姆酒代替卡莎萨。",
    "Campari Beer": "使用 15 oz 杯，先倒入金巴利，再以啤酒补满。",
    "Casino": "所有材料加冰充分摇匀，滤入冰镇鸡尾酒杯；饰以柠檬皮卷和马拉斯奇诺樱桃，不配吸管。",
    "Chocolate Drink": "将巧克力放入少量沸水中融化，加入牛奶，以小火加热并用打蛋器轻轻搅打；不要煮沸。倒入咖啡杯。",
    "Chocolate Milk": "shot 杯中先倒入牛奶，再缓慢倒入巧克力利口酒，最后滴入少量杏仁利口酒；不要搅拌，一口饮下。",
    "Citrus Coke": "杯中先倒入一半可口可乐，加入百加得柠檬朗姆酒，再以余下的可乐补满，搅匀。",
    "Coffee-Vodka": "水和糖煮至完全溶解后关火，慢慢加入速溶咖啡并持续搅拌。将切碎的香草荚加入伏特加，再与完全冷却的糖浆和咖啡液混合。密封后每天充分摇匀，持续 3 周，最后用细滤纸过滤。若想让口感更顺滑，可在成品中加入约 1 茶匙甘油。",
    "Cuba Libre": "高球杯装满冰块，依次加入朗姆酒和青柠汁，以可口可乐补满；饰以青柠角。",
    "Dark and Stormy": "高球杯加入冰块，倒入深色朗姆酒，再以姜汁啤酒补满；饰以青柠角。",
    "Dark Caipirinha": "古典杯中放入青柠角和德梅拉拉蔗糖并捣压，加满冰块后倒入卡莎萨，搅匀。",
    "Dirty Martini": "伏特加、干味美思和橄榄盐水加冰充分摇匀。用柠檬角擦拭马天尼杯杯口，将酒液滤入杯中，放入橄榄装饰。",
    "Dirty Nipple": "将 Kahlúa、Sambuca 和百利甜酒依次分层倒入 shot 杯，百利甜酒位于最上层。",
    "Diesel": "先倒入拉格啤酒，再加入黑加仑糖浆，以苹果酒补满；成品颜色应很深，接近健力士黑啤。",
    "Downshift": "杯中依次加入雪碧、龙舌兰酒和美汁源水果潘趣，最后将 151 proof 朗姆酒漂浮在酒面；可按需加冰。",
    "Drinking Chocolate": "淡奶油、牛奶、肉桂和香草荚以极小火加热 15–20 分钟；若没有香草荚，可在加热后加入 1–2 茶匙香草精。取出香草荚和肉桂，加入巧克力并搅至完全融化。倒入咖啡杯，顶部放上浓厚的现打奶油。此配方约为 1–2 人份；若想更浓郁，可将牛奶、淡奶油和巧克力各改为 4 oz。",
    "Dry Rob Roy": "苏格兰威士忌和干味美思倒入半杯冰的调酒杯，搅匀后滤入鸡尾酒杯；饰以柠檬皮卷。",
    "Dry Martini": "所有材料倒入调酒杯加冰搅拌，滤入冰镇马天尼杯；饰以橄榄或柠檬皮卷。",
    "Dubonnet Cocktail": "除柠檬皮外，所有材料加冰搅拌，滤入鸡尾酒杯；饰以柠檬皮卷。",
    "Egg Nog #4": "小碗中打散蛋黄，分次加入 1/4 杯糖，高速打至浓稠、颜色变浅。拌入牛奶、朗姆酒、波本威士忌、香草和盐，充分冷藏。另将淡奶油打发。清洗打蛋器后，将蛋白打至软性发泡，分次加入余下的 1/4 杯糖并打至硬性发泡。把蛋黄混合物和打发奶油轻轻拌入蛋白，立即倒入潘趣碗，分杯后撒肉豆蔻。无酒精版本可省略波本与朗姆酒，并把牛奶增至 3 杯。",
    "Egg Cream": "巧克力糖浆和牛奶在汽水杯中混合，加入苏打水，配吸管。",
    "Egg-Nog - Classic Cooked": "大锅中打匀鸡蛋、糖和盐，加入 2 杯牛奶搅匀。以小火持续搅拌，加热至混合物能挂在金属勺背、温度达到 160°F（约 71°C）。离火后拌入余下 2 杯牛奶和香草精，加盖冷藏数小时或过夜，至完全冰凉。饮用前倒入大碗或壶中，可按需加入巧克力卷、肉桂棒、食用香精、风味白兰地或利口酒、果汁、肉豆蔻粉、马拉斯奇诺樱桃、橙片、薄荷糖、白兰地、朗姆酒、威士忌、雪葩、冰淇淋或打发奶油，立即饮用。",
    "Elderflower Caipirinha": "将青柠和糖放入古典杯捣压，加入接骨木花糖浆、卡莎萨和碎冰，搅匀；饰以青柠片。",
    "English Highball": "白兰地、金酒和甜味美思倒入装有冰块的高球杯，以气泡水补满。加入柠檬皮卷并搅匀；也可用姜汁汽水代替气泡水。",
    "English Rose Cocktail": "用柠檬汁润湿鸡尾酒杯杯口并蘸糖粉。除樱桃外，所有材料加冰摇匀，滤入糖边杯；饰以樱桃。",
    "Espresso Martini": "所有材料加冰充分摇匀，滤入冰镇马天尼杯。",
    "Espresso Rumtini": "所有材料在鸡尾酒杯中混合，饰以可可粉和咖啡豆。",
    "Flaming Dr. Pepper": "将杏仁利口酒、百加得朗姆酒和伏特加混合，再加入胡椒博士汽水和啤酒。",
    "Flaming Lamborghini": "仅由专业调酒师操作。将 Kahlúa 和 Sambuca 倒入马天尼杯；百利甜酒与蓝橙力娇酒分别倒入两只 shot 杯。点燃主杯时不要饮用，必须先彻底熄灭，再将两只 shot 杯中的酒倒入并饮用。",
    "Flander's Flake-Out": "将两种材料直接倒入杯中。",
    "Frappé": "所有材料混合后，以搅拌机最高速搅打约 1 分钟，倒入杯中并配吸管。所有材料预先冰镇，成品会更理想；若使用现煮咖啡，可先与牛奶混合并冷藏约 30 分钟。泡沫不足时，可增加牛奶或奶粉。泡沫会逐渐化成冰咖啡沉到杯底，整杯可慢慢饮用约 30 分钟。",
    "Freddy Kruger": "将材料倒入容量稍大的 shot 杯。",
    "Frosé": "步骤 1\n将桃红葡萄酒倒入 13 × 9 in 烤盘，冷冻至少 6 小时至接近凝固；由于含有酒精，不会完全冻硬。\n\n步骤 2\n糖和 1/2 杯水放入中号锅中煮沸，持续搅拌约 3 分钟至糖完全溶解。加入草莓后离火，静置 30 分钟让风味融入糖浆。用细网筛滤入小碗，不要挤压果肉；加盖冷藏约 30 分钟至冰凉。\n\n步骤 3\n将冷冻桃红葡萄酒刮入搅拌机，加入柠檬汁、3.5 oz 草莓糖浆和 1 杯碎冰，打至顺滑。连搅拌杯冷冻 25–35 分钟，至接近奶昔的浓稠度。\n\n步骤 4\n再次搅打成冰沙状，分装入杯。\n\n步骤 5\n桃红葡萄酒最多可提前 1 周冷冻。",
    "Frozen Daiquiri": "除樱桃外，所有材料放入搅拌机，先以低速搅打 5 秒，再转高速打至质地浓稠。倒入笛形香槟杯，放上樱桃装饰。",
    "Frozen Mint Daiquiri": "所有材料与 1 杯碎冰放入搅拌机，短暂低速搅打后倒入古典杯。",
    "Frozen Pineapple Daiquiri": "所有材料与 1 杯碎冰放入搅拌机，短暂低速搅打后倒入鸡尾酒杯。",
    "Frisco Sour": "除柠檬片和青柠片外，所有材料加冰摇匀，滤入酸酒杯；饰以柠檬片和青柠片。",
    "Fruit Cooler": "草莓拌糖后冷藏一夜。柠檬切下两片留作装饰，其余榨汁；将柠檬汁、草莓、苹果汁和苏打水混合。杯中加入冰块和苹果片，倒入饮料，饰以柠檬片。",
    "Funk and Soul": "所有材料混合后滤入柯林杯。若想更贴近原配方风格，优先使用牙买加朗姆酒。",
    "Fuzzy Asshole": "咖啡杯中先倒入半杯热咖啡，再以桃味施纳普斯补满，搅匀后趁热饮用。",
    "Gagliardo": "所有材料充分摇匀，倒入鸡尾酒杯。",
    "GG": "杯中加冰，倒入加利安奴香草利口酒，再以姜汁汽水补满。",
    "Gin Fizz": "除苏打水外，所有材料加冰摇匀，滤入高球杯；以苏打水补满。",
    "Gin Sling": "糖粉用水和柠檬汁调匀，加入金酒。倒入装有冰块的古典杯并搅匀；饰以橙皮卷。",
    "Gin Smash": "古典杯中放入糖、气泡水和薄荷枝轻轻捣压，加入金酒和一块冰并搅匀；饰以橙片和樱桃。",
    "Gin Squirt": "金酒、红石榴糖浆和糖粉加冰搅拌，滤入装有冰块的高球杯；以气泡水补满并搅匀，饰以菠萝块和草莓。",
    "Gin Toddy": "古典杯中将糖粉与水调匀，加入金酒和一块冰并搅匀；饰以柠檬皮卷。",
    "Gluehwein": "糖和香料加水煮沸后浸泡 30 分钟。滤出香料水，与红葡萄酒混合，以小火加热至接近沸腾；可按口味加入柠檬汁或橙汁，倒入爱尔兰咖啡杯。若要降低酒精含量，可延长煮沸时间。",
    "Godchild": "所有材料加碎冰充分摇匀，滤入笛形香槟杯。",
    "Godmother": "伏特加和杏仁利口酒倒入装有冰块的古典杯。",
    "Grim Reaper": "杯中混合 Kahlúa 咖啡利口酒和 151 proof 朗姆酒，迅速加入冰块，再将红石榴糖浆淋在冰上，使冰块染上红色。",
    "Halloween Punch": "将樱桃汁、橙皮、辣椒、肉桂棒、丁香和姜放入大锅，小火煮 5 分钟后关火。冷却后冷藏至少 4 小时、最长 2 天；浸泡越久，风味越浓。若给儿童饮用，数小时后取出辣椒。饮用前倒入壶中分杯并配吸管；如需加入伏特加，在此时加入，最后在每只杯边挂一颗獠牙造型软糖。",
    "Happy Skipper": "杯中加冰，依次倒入香料朗姆酒和姜汁汽水，搅匀。",
    "Hemingway Special": "所有材料倒入加冰的摇酒壶，充分摇匀。",
    "Harvey Wallbanger": "伏特加和橙汁在杯中加冰搅匀，再将加利安奴香草利口酒漂浮在酒面；完成装饰。",
    "Highland Fling Cocktail": "除橄榄外，所有材料加冰搅拌，滤入鸡尾酒杯；饰以橄榄。",
    "Horse's Neck": "白兰地和姜汁汽水直接倒入装有冰块的高球杯，轻轻搅匀；饰以长条柠檬皮。可按口味加入安格仕芳香苦精。",
    "Hunter's Moon": "将孟买蓝宝石金酒、MARTINI Bianco 白味美思、糖浆和黑莓放入装有大量冰块的摇酒壶，充分摇匀后倒入气球杯，以柠檬汽水补满；饰以橙角。",
    "Hot Toddy": "将威士忌和蜂蜜搅匀后分入两个耐热杯，每杯放入半根肉桂棒，再分别加入 200 ml 沸水。各加入少量柠檬汁，按口味调整；最后饰以一片嵌入丁香的柠檬，立即饮用。",
    "Hot Chocolate to Die for": "巧克力、黄油和香草精放入隔水锅中融化；刚变得顺滑时，拌入 Half-and-half 稀奶油。",
    "Homemade Kahlua": "糖用 2 杯沸水溶解后加入玉米糖浆；速溶咖啡用余下的水溶解。将糖浆和咖啡液倒入 1 加仑壶中，完全冷却后加入伏特加和香草精。静置熟成 4–5 周，风味更佳。",
    "Iced Coffee": "咖啡、糖和热水搅至溶解，加入冷牛奶后充分摇匀。使用搅拌机或奶昔机可打出更丰富的泡沫；倒入咖啡杯。",
    "Irish Coffee": "咖啡、爱尔兰威士忌和糖加热但不要煮沸，倒入杯中，顶部放上打发奶油，趁热饮用。",
    "Irish Cream": "将苏格兰威士忌和牛奶混合，加入 Half-and-half 稀奶油，再加入炼乳、椰子糖浆和巧克力糖浆，搅匀。",
    "Irish Spring": "除橙片和樱桃外，所有材料倒入装有冰块的柯林杯；饰以橙片和樱桃。",
    "Ipamena": "半个青柠切块放入摇酒壶，加入红糖捣压。倒入百香果汁，加满冰后充分摇匀。倒入杯中，以姜汁汽水补满，用茶匙搅匀；饰以青柠片。",
    "Jack's Vanilla Coke": "材料倒入杯中，按口味加入 3–5 块冰，用搅拌棒充分搅匀，让沉在杯底的香草糖浆混合开。",
    "Jamaica Kiss": "平底杯装入冰块，加入一 shot 咖啡利口酒和一 shot 牙买加白朗姆酒，再以牛奶补满。搅打至顺滑后立即饮用。",
    "Jamaican Coffee": "将朗姆酒、浓黑咖啡和冷水搅匀，顶部放上打发奶油，撒少量细磨咖啡粉；配吸管。",
    "Jelly Bean": "黑莓白兰地和茴香酒按等量倒入小酒杯混合。",
    "Jackhammer": "两种材料混合后加冰饮用；酒精度较高，请适量。",
    "Jitterbug": "润湿杯口并蘸糖，杯中加冰后倒入其余材料；以苏打水补满。",
    "Jam Donut": "用糖浆润湿 shot 杯杯口并蘸糖。倒入香博覆盆子利口酒，再沿吧勺背面缓慢倒入百利甜酒，使其浮在上层。",
    "Kentucky B And B": "将波本威士忌和廊酒倒入白兰地杯中混合。",
    "Kentucky Colonel": "将波本威士忌和廊酒倒入古典杯加冰搅匀；饰以柠檬皮卷。",
    "Kioki Coffee": "爱尔兰咖啡杯中加入 Kahlúa 咖啡利口酒和白兰地，以热咖啡补满；顶部放上打发奶油。",
    "Kir": "黑加仑利口酒倒入杯底，再以葡萄酒补满。",
    "Kir Royale": "黑加仑利口酒倒入笛形香槟杯，以冰镇香槟补满。",
    "Kiwi Martini": "猕猴桃片与糖浆放入摇酒壶捣压，加入伏特加和冰充分摇匀，双重滤入冰镇马天尼杯。",
    "Kool-Aid Slammer": "shot 杯先倒入半杯调好的 Kool-Aid。用纸巾覆盖杯口，沿纸巾缓慢倒入伏特加，使两种液体保持分层；一口饮下，最后尝到的是 Kool-Aid。",
    "Kurant Tea": "绝对伏特加黑加仑味倒入大茶杯，加入温热但不过烫的苹果茶；可按口味加糖。",
    "Kamikaze": "所有材料加冰摇匀，滤入杯中，完成装饰。",
    "Kill the cold Smoothie": "姜和柠檬榨汁后加入热水；可按口味加入小豆蔻。",
    "Lassi - A South Indian Drink": "所有材料放入搅拌机搅打约 3 秒。拉西是酸奶加水搅成的饮品，可按喜好调整浓稠度，冰镇饮用。",
    "Lassi - Mango": "所有材料放入搅拌机打匀，倒在碎冰上；也可用草莓、香蕉等水果替换芒果。",
    "Lassi - Sweet": "所有材料倒入搅拌机打至顺滑，冰镇饮用。",
    "Lassi Khara": "所有材料倒入搅拌机打匀，冰镇饮用。",
    "Lassi Raita": "酸奶和冰块搅打至质地变稀，按口味加糖和少量盐；柠檬或青柠可选，会带来轻微酸味。冰镇饮用。",
    "Lemon Drop": "所有材料加冰摇匀，滤入杯口蘸糖的冰镇鸡尾酒杯。",
    "Lazy Coconut Paloma": "椰子利口酒与葡萄柚汁混合，以苏打水补满；在杯内侧放一大片葡萄柚装饰。",
    "Lady Love Fizz": "除气泡水外，所有材料加冰摇匀，滤入装有两块冰的鸡尾酒杯；以气泡水补满并搅匀。",
    "Lemon Elderflower Spritzer": "所有材料倒在冰块上，搅匀。",
    "Lemouroudji": "柠檬榨汁，姜去皮后磨碎。姜末和足量卡宴辣椒粉包入纱布并扎紧，放入水中浸泡约 15 分钟，再加入糖和柠檬汁；冰镇后饮用。",
    "Limeade": "大杯中放入青柠汁和糖，搅至溶解；以冰镇苏打水补满，加入青柠皮。",
    "Limona Corona": "打开科罗娜啤酒，向瓶颈空隙中倒入朗姆酒至满。用拇指或掌心盖紧瓶口，将瓶子倒转一次使两种酒混合，再转回正向，移开手掌后饮用。",
    "Loch Lomond": "苏格兰威士忌、杜林标利口酒和干味美思倒入半杯冰的调酒杯，搅匀后滤入鸡尾酒杯；饰以柠檬皮卷。",
    "Lord And Lady": "深色朗姆酒和添万利咖啡利口酒倒入接近加满冰的古典杯，搅匀。",
    "Lone Tree Cooler": "柯林杯中加入糖粉和 2 oz 气泡水，搅至溶解。加满冰后加入金酒和干味美思并搅匀，再以气泡水补满。加入柠檬皮卷和螺旋橙皮，让橙皮一端垂在杯沿外。",
    "Long Island Iced Tea": "所有材料在高球杯中混合并轻轻搅匀，加入少量可口可乐上色；饰以柠檬皮卷或青柠皮卷。",
    "Long Island Tea": "除可乐外，所有材料混合后倒在高球杯的冰块上；加入少量可乐上色，饰以柠檬片。",
    "Lunch Box": "品脱杯中倒入啤酒至接近满杯，再加入橙汁，但保留少量空间；最后把一整杯杏仁利口酒连同 shot 杯投入其中。",
    "Mango Mojito": "将 1.5 个青柠榨汁，与芒果打成顺滑果泥。其余青柠切成小块；每只高球杯放入 2 块青柠、1 茶匙细砂糖和 5–6 片薄荷叶，用捣棒压出汁液和香气。分入芒果泥，每杯加入 30 ml 白朗姆酒和一把碎冰，搅匀后以苏打水补满；可另饰薄荷。",
    "Manhattan": "所有材料加冰搅拌，滤入冰镇杯；完成装饰后不加冰饮用。",
    "Mai Tai": "所有材料加冰摇匀，滤入杯中；完成装饰并配吸管。",
    "Masala Chai": "2 杯水煮沸，加入茶叶、姜、小豆蔻、丁香、肉桂和黑胡椒，再煮约 15 秒，静置 1 分钟。另将牛奶加热，把茶滤入杯中，再按口味加入热牛奶和糖。",
    "Mauresque": "先倒入力加茴香酒，再加入杏仁糖浆，最后倒入水并按需加冰。冰块要最后加入，否则杏仁糖浆不易与茴香酒混合均匀。",
    "Melya": "先萃取浓缩咖啡。咖啡杯中放入 1 茶匙无糖可可粉，再淋入 1 茶匙蜂蜜，耐心搅拌至形成深色巧克力酱。倒入热浓缩咖啡并搅至溶解，配淡奶油。",
    "Miami Vice": "先将椰林飘香预调液、2.5 oz 朗姆酒和冰打匀，放置备用；再将代基里预调液、2.5 oz 朗姆酒和冰打匀。两种冰沙依次倒入同一只杯中，保持分层，不要混在一起。",
    "Michelada": "用青柠润湿杯口并蘸盐。杯中加冰，依次加入啤酒、青柠汁和调味料，轻轻搅匀；饰以青柠角。",
    "Mint Julep": "朱莉普杯中轻轻捣压薄荷与糖浆，加入波本威士忌和碎冰，搅至杯壁挂霜；再补满碎冰，饰以薄荷。",
    "Midnight Mint": "可先用糖浆润湿鸡尾酒杯杯口，并蘸巧克力碎或可可粉。所有材料加冰摇匀，滤入杯中。",
    "Mimosa": "香槟和橙汁充分冰镇后倒入杯中混合，冰镇饮用。",
    "Mocha-Berry": "咖啡杯或爱尔兰咖啡杯中倒入 6 oz 咖啡，加入可可粉和香博覆盆子利口酒并搅匀，顶部放上打发奶油。",
    "National Aquarium": "所有材料倒入装有冰块的摇酒壶，充分摇匀后加冰饮用。",
    "Mojito": "薄荷叶、糖和青柠汁轻轻捣压，加入少量苏打水并用碎冰装满杯子。倒入白朗姆酒，再以苏打水补满；完成装饰并配吸管。",
    "Mojito Extra": "杯中放入薄荷和柠檬汁，用勺子轻轻捣压薄荷。加入冰块和牙买加深色朗姆酒，以苏打水补满；最后滴入安格仕芳香苦精。",
    "Monkey Gland": "所有材料加冰充分摇匀，滤入冰镇鸡尾酒杯。",
    "Negroni": "所有材料倒入装有冰块的杯中搅匀，完成装饰。",
    "New York Lemonade": "鸡尾酒杯预先冰镇，用柠檬润湿杯口并蘸糖。所有材料加冰搅拌后滤入杯中。",
    "New York Sour": "威士忌、柠檬汁和糖粉加冰摇匀，滤入酸酒杯；将红葡萄酒漂浮在酒面，饰以半片柠檬和樱桃。",
    "Nuked Hot Chocolate": "咖啡杯中先用约 1 oz 牛奶调开可可粉，微波加热 30–50 秒后搅至溶解。以牛奶补满，再按微波炉功率加热 1–2 分钟；避免过热，以免烫伤。",
    "Old Cuban": "薄荷、白朗姆酒、糖浆、青柠汁和安格仕芳香苦精加冰摇匀，双重滤入杯中，再以普罗塞克起泡酒补满。",
    "Old Fashioned": "古典杯中放入方糖，以苦精浸透并加入少量水，捣压至糖溶解。加满冰块后倒入威士忌；饰以橙皮卷和糖渍樱桃。",
    "Orange Push-up": "所有酒液倒入搅拌机，加入半勺冰打匀；饰以橙片和樱桃。",
    "Orange Crush": "所有材料倒入平底杯混合，以 shot 方式饮用。",
    "Orange Rosemary Collins": "烈酒倒入杯底，分别加入等量橙汁、柠檬汁和苏打水，再加入迷迭香糖浆；杯内放入橙片，顶部饰以迷迭香。",
    "Orange Scented Hot Chocolate": "所有材料放入厚底中号锅，以小火搅拌至巧克力融化。调高火力，加热至刚沸腾并经常搅拌；离火搅打至起泡。再重复一次加热至沸腾、离火搅打的过程，最后再重复一次，取出橙皮。倒入咖啡杯，约为 2 人份。可提前 2 小时制作并在室温静置；饮用前重新加热至刚沸腾，离火搅打至起泡。",
    "Paradise": "所有材料加冰摇匀，滤入鸡尾酒杯，冰镇饮用。",
    "Pina Colada": "所有材料与碎冰放入搅拌机打至顺滑，倒入冰镇杯，完成装饰。",
    "Pink Moon": "所有材料加冰轻柔摇匀，滤入方形威士忌杯，再加入新冰；饰以黑莓，也可加入可食用花朵和绿叶。",
    "Pisco Sour": "所有材料加冰充分摇匀，滤入杯中；以苦精装饰。",
    "Oreo Mudslide": "伏特加、Kahlúa 咖啡利口酒、百利甜酒、香草冰淇淋和奥利奥饼干放入搅拌机打匀，倒入冰镇大杯；饰以打发奶油和樱桃。",
    "Planter's Punch": "除苦精外，所有材料倒入装有冰块的摇酒壶，充分摇匀后连冰倒入大杯。将安格仕芳香苦精滴在酒面，饰以糖渍樱桃和菠萝。",
    "Planter’s Punch": "鲜榨橙汁滤去果渣。所有材料放入装有冰块的摇酒壶，摇匀至少 12 秒，滤入高球杯；饰以菠萝角或其他水果。",
    "Pornstar Martini": "除普罗塞克外，所有材料加冰充分摇匀，滤入冰镇马天尼杯；以半颗百香果装饰。普罗塞克另倒入冰镇 shot 杯，随酒一同上桌。",
    "Popped cherry": "高杯加冰后倒入所有材料，饰以樱桃；也可按喜好多加几颗。",
    "Port And Starboard": "将红石榴糖浆倒入 pousse-café 分层杯，再缓慢倒入绿色薄荷利口酒，使其浮在上层；不要搅拌。",
    "Porto flip": "所有材料加冰摇匀，滤入杯中，完成装饰。",
    "Pure Passion": "所有材料用吧勺搅匀，加入碎冰；饰以薄荷和可食用花朵。",
    "Quentin": "深色朗姆酒、Kahlúa 咖啡利口酒和稀奶油倒入加冰至半满的摇酒壶，充分摇匀后滤入鸡尾酒杯；饰以肉豆蔻粉。",
    "Quick F**K": "shot 杯中依次分层倒入等量 Kahlúa 咖啡利口酒、蜜多丽蜜瓜利口酒和百利甜酒。",
    "Ramos Gin Fizz": "所有材料先不加冰，放入摇酒壶用力干摇约 1 分钟，让淡奶油和蛋白充分乳化。加入冰块后再摇 1–2 分钟，滤入高球杯，加入少量苏打水；按喜好装饰。",
    "Royal Bitch": "shot 杯中先倒入 Frangelico 榛果利口酒，再沿吧勺背面缓慢倒入 Crown Royal 加拿大威士忌，使其浮在上层。",
    "Ruby Tuesday": "高球杯加满冰，倒入金酒和蔓越莓汁，加入红石榴糖浆并搅匀。",
    "Raspberry Julep": "杯底放入薄荷叶和覆盆子糖浆轻轻捣压，加入碎冰和波本威士忌并搅匀；再补碎冰，饰以薄荷枝。",
    "Rosemary Blue": "气球杯中加入孟买蓝宝石金酒、蓝橙力娇酒、迷迭香枝和轻挤出汁的柠檬角，旋杯混匀。加满冰块，以 Fever-Tree 低糖汤力水补满，再用吧勺轻轻提拉搅匀。",
    "Rose": "所有材料加冰摇匀，滤入冰镇杯，完成装饰。",
    "Royal Fizz": "除可口可乐外，所有材料加冰摇匀，滤入冰镇柯林杯；以可口可乐补满。",
    "San Francisco": "高杯加入几块冰，依次倒入伏特加、橙汁和香蕉利口酒；最后沿杯壁缓慢倒入红石榴糖浆，使其沉到底部。饰以橙片和草莓。",
    "Salty Dog": "所有材料倒入装有冰块的高球杯，充分搅匀；也可用伏特加代替金酒。",
    "Rusty Nail": "苏格兰威士忌和杜林标利口酒倒入接近加满冰的古典杯，搅匀；饰以柠檬皮卷。",
    "Sazerac": "用苦艾酒润洗冰镇古典杯，加入碎冰后放置备用。其余材料另加冰搅拌。倒掉杯中的冰和多余苦艾酒，将酒液滤入杯中；饰以柠檬皮。",
    "Shark Attack": "按照包装说明用水调开浓缩柠檬饮料，倒入壶中；加入 1.5 杯绝对伏特加并搅匀，倒入装有碎冰的杯中。",
    "Shot-gun": "shot 杯中倒入等量杰克丹尼威士忌和占边波本威士忌，再将野火鸡波本威士忌漂浮在酒面。",
    "Screwdriver": "伏特加和橙汁倒入装有冰块的高球杯中混合，完成装饰。",
    "Snowball": "杯中放入一块冰，加入 1.5 oz 荷兰蛋黄酒，以冰镇柠檬汽水补满；饰以柠檬片，立即饮用。",
    "Space Odyssey": "杯中加满冰，加入百加得 151 proof 朗姆酒和马利宝椰子朗姆酒，再加入少量菠萝汁，以橙汁补满。加入红石榴糖浆调色，饰以樱桃。",
    "Spice 75": "锅中放入 60 g 金黄细砂糖、30 ml 水和 1 汤匙多香果，以小火加热至糖溶解，冷却后用铺有咖啡滤纸或双层厨房纸的筛网过滤。取 60 ml 香料糖浆，与 200 ml 朗姆酒和 90 ml 青柠汁放入摇酒壶，加冰摇匀后分滤入 6 只笛形香槟杯。每杯以香槟补满，饰以橙皮卷。",
    "Sol Y Sombra": "所有材料加冰摇匀，滤入白兰地杯。酒名在西班牙语中意为“日与影”。",
    "Sweet Sangria": "糖用热水溶解后放凉。柑橘类水果去皮并分成小块，与葡萄酒、糖浆和 Fresca 汽水一起倒入壶中混合，冷藏数小时；倒入高杯，配吸管。",
    "Sweet Tooth": "杯中倒入 2 shot 歌帝梵巧克力利口酒，再按口味加入牛奶。",
    "Talos Coffee": "杯中先倒入 Grand Marnier 橙酒，再加入咖啡。",
    "Thai Coffee": "将咖啡粉和香料放入咖啡机滤杯，照常冲煮后放凉。高杯中用 1 oz 咖啡溶解 1–2 茶匙糖，加入 5–6 块冰，再倒入咖啡至离杯口约 1 in。把勺子贴近咖啡表面，沿勺背缓慢倒入淡奶油，使其浮在上层。",
    "Tennesee Mud": "混合咖啡、杰克丹尼威士忌和杏仁利口酒，顶部放上淡奶油。",
    "Tequila Slammer": "将龙舌兰酒和七喜小心混合，避免二氧化碳过快逸出。",
    "Texas Rattlesnake": "所有材料混合后充分摇匀；入口偏甜，尾段带有明显辛辣感。",
    "Tequila Sunrise": "龙舌兰酒和橙汁倒入装有冰块的杯中，再加入会沉到底部的红石榴糖浆；轻轻搅动形成日出渐层，完成装饰。",
    "Texas Sling": "所有材料加冰打至顺滑，倒入郁金香杯，顶部放上打发奶油。",
    "The Galah": "先将深色朗姆酒、金巴利和香蕉利口酒混合，再以菠萝汁和青柠汁补满。",
    "The Jimmy Conway": "杯中加满冰，倒入 The Irishman 爱尔兰威士忌和 Disaronno 杏仁利口酒，再以蔓越莓汁补满；饰以柠檬片。",
    "The Philosopher": "金酒、蜜瓜利口酒、橙味苦精和柠檬汁放入摇酒壶混合，滤入玛格丽特杯，再以普罗塞克起泡酒补满；金酒以 Hendrick's 为佳。",
    "The Laverstoke": "将两块青柠角挤汁入气球杯，加入接骨木花糖浆、孟买蓝宝石金酒和 MARTINI Rosso 红味美思，旋杯混匀。杯中加满冰块并搅拌至冰镇，以 Fever-Tree 姜汁汽水补满后轻轻搅匀；饰以轻折出香气的姜片和拍醒的薄荷枝。",
    "Vesper": "所有材料加冰摇至充分冰镇，滤入深杯；饰以一片薄柠檬皮。",
    "Vermouth Cassis": "干味美思和黑加仑利口酒倒入装有冰块的高球杯搅匀，以气泡水补满后再次搅匀。",
    "Vodka Russian": "伏特加与怡泉 Russchian 汽水混合。",
    "Vodka Lemon": "高球杯或大平底杯中加入 6–7 块冰，倒入伏特加和柠檬汽水，用吧勺搅匀；饰以柠檬片，也可加入几片薄荷叶。",
    "Vodka Martini": "伏特加和干味美思加冰摇匀，滤入鸡尾酒杯；饰以橄榄。",
    "Vodka Slime": "杯中加满冰，依次倒入伏特加和雪碧，最后加入青柠汁。",
    "White Wine Sangria": "柠檬、青柠和其他水果切成大块放入壶中，加入白葡萄酒和苹果白兰地混合，再按口味以苏打水补满。",
    "White Russian": "伏特加和咖啡利口酒倒入装有冰块的古典杯，以稀奶油补满。",
    "Whitecap Margarita": "所有材料放入搅拌机打至顺滑；此配方为 1 杯份。",
    "Winter Paloma": "这款帕洛玛以印度风味重新演绎：将带有柑橘和葡萄柚气息的喜马拉雅 Timur 胡椒浸入陈年龙舌兰酒，并用喜马拉雅暖香料调味鲜榨葡萄柚汁。入口时，Timur 胡椒会在唇边带来轻微的麻感。",
    "Winter Rita": "杯口蘸盐。所有材料加冰摇匀，滤入装有新冰的杯中。",
    "Zima Blaster": "杯中加满冰，先倒入香博覆盆子利口酒，再以 Zima 麦芽汽水补满并搅匀。",
    "Zippy's Revenge": "按口味调好 Kool-Aid，加入朗姆酒和杏仁利口酒，充分摇匀使糖溶解，冰镇饮用。",
    "Zombie": "所有材料以高速搅打不超过 5 秒，倒入杯中并加冰至满，最后完成装饰。\n\nDonn's Mix：3 根压碎的肉桂棒、1 杯糖和 1 杯水煮沸，搅至糖溶解。小火煮 2 分钟后离火，静置至少 2 小时，再滤入干净玻璃瓶。使用时，将 1 份肉桂糖浆与 2 份鲜榨葡萄柚汁混合。",
    "Zizi Coin-coin": "5 cl 君度橙酒倒在冰块上，加入 2 cl 鲜榨柠檬汁或青柠汁，轻轻搅匀；最后加入柠檬片或青柠片。",
    "Zorro": "所有材料混合后加入黑咖啡，顶部放上打发奶油。",
})


REPLACEMENTS = (
    ("鸡尾酒调酒器", "摇酒壶"),
    ("玻璃搅拌器", "调酒杯"),
    ("玻璃混合器", "调酒杯"),
    ("调酒器", "摇酒壶"),
    ("双层老式玻璃杯", "双份古典杯"),
    ("老式玻璃杯", "古典杯"),
    ("岩石玻璃杯", "古典杯"),
    ("岩石杯", "古典杯"),
    ("柯林斯玻璃杯", "柯林杯"),
    ("高球玻璃杯", "高球杯"),
    ("高脚玻璃杯", "高球杯"),
    ("气球玻璃杯", "气球杯"),
    ("酸玻璃杯", "酸酒杯"),
    ("小玻璃杯", "shot 杯"),
    ("射手杯", "shot 杯"),
    ("射手", "shot"),
    ("射击", "一口饮下"),
    ("每人一枪", "每款各取 1 shot"),
    ("杜松子酒", "金酒"),
    ("苦味剂", "苦精"),
    ("苦味酒", "苦精"),
    ("干苦艾酒", "干味美思"),
    ("甜苦艾酒", "甜味美思"),
    ("三秒酒", "白橙皮利口酒"),
    ("酸橙", "青柠"),
    ("石灰轮", "青柠片"),
    ("青柠轮", "青柠片"),
    ("石灰", "青柠"),
    ("滋补品", "汤力水"),
    ("补品", "汤力水"),
    ("糖醋", "酸甜预调液"),
    ("简单糖浆", "糖浆"),
    ("酸果蔓", "蔓越莓"),
    ("楔形物", "果角"),
    ("橙色麻花", "橙皮卷"),
    ("冷玻璃杯", "冰镇杯"),
    ("冰镇的玻璃杯", "冰镇杯"),
    ("冰镇的杯", "冰镇杯"),
    ("搅拌杯", "调酒杯"),
    ("鸡尾酒搅拌器", "吧勺"),
    ("轿跑车杯", "碟形香槟杯"),
    ("摇床", "摇酒壶"),
    ("稻草", "吸管"),
    ("玻璃杯", "杯"),
    ("冷却杯", "冰镇杯"),
    ("玻璃结霜", "杯壁挂霜"),
    ("成分", "材料"),
    ("配料", "材料"),
    ("内容物", "酒液"),
    ("添加", "加入"),
    ("填充", "加满"),
    ("分层放入", "依次分层倒入"),
    ("即可食用", "即可"),
    ("即可享用", "即可"),
    ("加冰食用", "加冰饮用"),
    ("食用", "饮用"),
    ("服务。", "完成。"),
    ("上菜", "完成"),
    ("上桌", "完成"),
    ("享受！", "即可。"),
    ("享用！", "即可。"),
    ("在上面撒上", "撒上"),
    ("上面撒上", "撒上"),
    ("剧烈摇晃", "充分摇匀"),
    ("猛击它", "一口饮下"),
    ("镜头", "shot"),
    ("冲床", "潘趣"),
    ("搅打至光滑", "打至顺滑"),
    ("搅拌直至光滑", "打至顺滑"),
    ("混乱", "捣压"),
    ("薄荷枝", "薄荷枝"),
    ("鸡尾酒振动筛", "摇酒壶"),
    ("苦杏酒", "杏仁利口酒"),
    ("生奶油", "打发奶油"),
    ("安古斯图拉", "安格仕"),
    ("柯林斯杯", "柯林杯"),
    ("所有原料", "所有材料"),
    ("原料", "材料"),
    ("，即可。", "。"),
    ("即可。", "。"),
)


def clean_instruction(name: str, value: str, english: str) -> str:
    if name in INSTRUCTION_OVERRIDES:
        return INSTRUCTION_OVERRIDES[name]
    if english in ENGLISH_TEMPLATES:
        return ENGLISH_TEMPLATES[english]
    result = value.replace("\u200b", "").replace("\u200a", "").replace("\u2060", "")
    for source, target in REPLACEMENTS:
        result = result.replace(source, target)
    result = re.sub(r"[ \t]+", " ", result)
    result = re.sub(r" *\n *", "\n", result)
    result = re.sub(r"\n{3,}", "\n\n", result)
    result = re.sub(r" +([，。；：！？])", r"\1", result)
    return result.strip()


def clean_name(name: str, value: str) -> str:
    result = NAME_OVERRIDES.get(name, value)
    result = result.replace("菲兹", "菲士").replace("宾治", "潘趣")
    result = result.replace("戴吉利", "代基里").replace("代基里酒", "代基里")
    return result


def main() -> None:
    payload = json.loads(RECIPES_PATH.read_text())
    names = json.loads(NAMES_PATH.read_text())
    instructions = {}

    for recipe in payload["recipes"]:
        recipe["nameZh"] = clean_name(recipe["name"], names.get(recipe["name"], recipe.get("nameZh") or recipe["name"]))
        recipe["instructions"]["zh"] = clean_instruction(
            recipe["name"],
            recipe["instructions"].get("zh", ""),
            recipe["instructions"].get("en", ""),
        )
        names[recipe["name"]] = recipe["nameZh"]
        instructions[recipe["id"]] = recipe["instructions"]["zh"]

    ordered_names = {key: names[key] for key in sorted(names, key=str.casefold)}
    ordered_instructions = {key: instructions[key] for key in sorted(instructions)}
    RECIPES_PATH.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n")
    NAMES_PATH.write_text(json.dumps(ordered_names, ensure_ascii=False, indent=2) + "\n")
    INSTRUCTIONS_PATH.write_text(json.dumps(ordered_instructions, ensure_ascii=False, indent=2) + "\n")
    print(f"Localized {len(instructions)} instructions and {len(ordered_names)} names")


if __name__ == "__main__":
    main()
