window.CocktailTerms = (() => {
  const ingredients = {
    "151 proof rum": "151 proof 朗姆酒",
    "7-up": "七喜",
    "absinthe": "苦艾酒",
    "absolut citron": "绝对伏特加柠檬味",
    "absolut kurant": "绝对伏特加黑加仑味",
    "absolut peppar": "绝对伏特加辣椒味",
    "absolut vodka": "绝对伏特加",
    "advocaat": "荷兰蛋黄酒",
    "agave syrup": "龙舌兰糖浆",
    "allspice": "多香果",
    "almond flavoring": "杏仁香精",
    "amaretto": "杏仁利口酒",
    "amaro montenegro": "黑山阿玛罗利口酒",
    "angostura bitters": "安格仕芳香苦精",
    "anis": "茴香酒",
    "anisette": "茴香甜酒",
    "aperol": "阿佩罗",
    "apfelkorn": "苹果谷物烈酒",
    "apple": "苹果",
    "apple brandy": "苹果白兰地",
    "apple juice": "苹果汁",
    "applejack": "Applejack 苹果白兰地",
    "apricot brandy": "杏桃白兰地",
    "apricot nectar": "杏桃果露",
    "asafoetida": "阿魏",
    "añejo rum": "陈年朗姆酒",
    "bacardi limon": "百加得柠檬朗姆酒",
    "baileys irish cream": "百利甜酒",
    "banana": "香蕉",
    "banana liqueur": "香蕉利口酒",
    "beer": "啤酒",
    "benedictine": "廊酒",
    "bitter lemon": "苦柠檬汽水",
    "bitters": "苦精",
    "black pepper": "黑胡椒",
    "black sambuca": "黑色桑布卡",
    "blackberries": "黑莓",
    "blackberry brandy": "黑莓白兰地",
    "blackcurrant cordial": "黑加仑果露",
    "blackstrap rum": "黑糖蜜朗姆酒",
    "blended scotch": "调和苏格兰威士忌",
    "blended whiskey": "调和威士忌",
    "blood orange": "血橙",
    "blue curacao": "蓝橙力娇酒",
    "blueberry schnapps": "蓝莓施纳普斯",
    "bourbon": "波本威士忌",
    "brandy": "白兰地",
    "brown sugar": "红糖",
    "butter": "黄油",
    "butterscotch schnapps": "奶油糖施纳普斯",
    "cachaca": "卡莎萨",
    "campari": "金巴利",
    "caramel coloring": "焦糖色",
    "carbonated soft drink": "碳酸饮料",
    "carbonated water": "气泡水",
    "cardamom": "小豆蔻",
    "cayenne pepper": "卡宴辣椒粉",
    "celery salt": "芹盐",
    "chambord raspberry liqueur": "香博覆盆子利口酒",
    "champagne": "香槟",
    "cherries": "樱桃",
    "cherry": "樱桃",
    "cherry brandy": "樱桃白兰地",
    "cherry heering": "喜灵樱桃利口酒",
    "cherry juice": "樱桃汁",
    "cherry liqueur": "樱桃利口酒",
    "chocolate": "巧克力",
    "chocolate liqueur": "巧克力利口酒",
    "chocolate syrup": "巧克力糖浆",
    "cider": "苹果酒",
    "cinnamon": "肉桂",
    "cloves": "丁香",
    "club soda": "苏打水",
    "coca-cola": "可口可乐",
    "cocoa powder": "可可粉",
    "coconut liqueur": "椰子利口酒",
    "coconut milk": "椰奶",
    "coconut syrup": "椰子糖浆",
    "coffee": "咖啡",
    "coffee brandy": "咖啡白兰地",
    "coffee liqueur": "咖啡利口酒",
    "cognac": "干邑",
    "cointreau": "君度橙酒",
    "condensed milk": "炼乳",
    "coriander": "芫荽籽",
    "corn syrup": "玉米糖浆",
    "corona": "科罗娜啤酒",
    "cranberry juice": "蔓越莓汁",
    "cranberry vodka": "蔓越莓伏特加",
    "cream": "淡奶油",
    "cream of coconut": "椰浆",
    "creme de banane": "香蕉利口酒",
    "creme de cacao": "可可利口酒",
    "creme de cassis": "黑加仑利口酒",
    "creme de mure": "黑莓利口酒",
    "crown royal": "皇冠威士忌",
    "cucumber": "黄瓜",
    "cumin seed": "孜然籽",
    "daiquiri mix": "代基里预调液",
    "dark creme de cacao": "深色可可利口酒",
    "dark rum": "深色朗姆酒",
    "demerara sugar": "德梅拉拉蔗糖",
    "dr. pepper": "胡椒博士汽水",
    "drambuie": "杜林标利口酒",
    "dry vermouth": "干味美思",
    "dubonnet rouge": "杜本内红味美思",
    "egg": "鸡蛋",
    "egg white": "蛋清",
    "egg yolk": "蛋黄",
    "elderflower cordial": "接骨木花果露",
    "espresso": "浓缩咖啡",
    "everclear": "Everclear 谷物烈酒",
    "falernum": "法勒南风味糖浆",
    "figs": "无花果",
    "firewater": "高浓度烈酒",
    "frangelico": "芳津杏仁利口酒",
    "fresca": "Fresca 柚子汽水",
    "fresh lemon juice": "鲜榨柠檬汁",
    "fresh lime juice": "鲜榨青柠汁",
    "fruit": "水果",
    "fruit juice": "果汁",
    "fruit punch": "水果潘趣",
    "galliano": "加利安奴香草利口酒",
    "gin": "金酒",
    "ginger": "姜",
    "ginger ale": "姜汁汽水",
    "ginger beer": "姜汁啤酒",
    "ginger syrup": "姜糖浆",
    "godiva liqueur": "歌帝梵巧克力利口酒",
    "gold rum": "金朗姆酒",
    "goldschlager": "金箔肉桂利口酒",
    "grain alcohol": "谷物烈酒",
    "grand marnier": "金万利橙酒",
    "grape juice": "葡萄汁",
    "grape soda": "葡萄汽水",
    "grapefruit juice": "西柚汁",
    "green chartreuse": "绿夏翠丝",
    "green creme de menthe": "绿色薄荷利口酒",
    "grenadine": "红石榴糖浆",
    "guinness stout": "健力士黑啤",
    "half-and-half": "半奶油半牛奶",
    "heavy cream": "浓奶油",
    "honey": "蜂蜜",
    "honey syrup": "蜂蜜糖浆",
    "hot chocolate": "热巧克力",
    "hot damn": "Hot Damn 肉桂利口酒",
    "hot sauce": "辣椒酱",
    "ice": "冰",
    "iced tea": "冰茶",
    "irish cream": "爱尔兰奶油利口酒",
    "irish whiskey": "爱尔兰威士忌",
    "islay single malt scotch": "艾雷岛单一麦芽威士忌",
    "jack daniels": "杰克丹尼威士忌",
    "jagermeister": "野格利口酒",
    "jägermeister": "野格利口酒",
    "jello": "果冻粉",
    "jim beam": "占边波本威士忌",
    "johnnie walker": "尊尼获加威士忌",
    "kahlua": "甘露咖啡利口酒",
    "kiwi": "奇异果",
    "kiwi liqueur": "奇异果利口酒",
    "kool-aid": "Kool-Aid 冲饮粉",
    "lager": "拉格啤酒",
    "lavender": "薰衣草",
    "lemon": "柠檬",
    "lemon juice": "柠檬汁",
    "lemon peel": "柠檬皮",
    "lemon-lime soda": "柠檬青柠汽水",
    "lemonade": "柠檬汽水",
    "light cream": "淡奶油",
    "light rum": "白朗姆酒",
    "lillet": "利莱开胃酒",
    "lillet blanc": "白利莱",
    "lime": "青柠",
    "lime juice": "青柠汁",
    "lime peel": "青柠皮",
    "lime vodka": "青柠伏特加",
    "limeade": "青柠饮料",
    "malibu rum": "马利宝椰子朗姆酒",
    "mango": "芒果",
    "maple syrup": "枫糖浆",
    "maraschino cherry": "马拉斯奇诺樱桃",
    "maraschino liqueur": "马拉斯奇诺利口酒",
    "marshmallows": "棉花糖",
    "melon liqueur": "蜜瓜利口酒",
    "mezcal": "梅斯卡尔",
    "midori melon liqueur": "蜜多丽蜜瓜利口酒",
    "milk": "牛奶",
    "mint": "薄荷",
    "mint syrup": "薄荷糖浆",
    "mountain dew": "激浪汽水",
    "nutmeg": "肉豆蔻",
    "olive": "橄榄",
    "olive brine": "橄榄盐水",
    "orange": "橙子",
    "orange bitters": "橙味苦精",
    "orange curacao": "橙味库拉索酒",
    "orange juice": "橙汁",
    "orange peel": "橙皮",
    "orange spiral": "螺旋橙皮",
    "oreo cookie": "奥利奥饼干",
    "orgeat syrup": "杏仁糖浆",
    "ouzo": "乌佐茴香酒",
    "papaya": "木瓜",
    "passion fruit juice": "百香果汁",
    "passion fruit syrup": "百香果糖浆",
    "passoa": "Passoã 百香果利口酒",
    "peach bitters": "桃味苦精",
    "peach brandy": "桃子白兰地",
    "peach nectar": "桃子果露",
    "peach schnapps": "桃味施纳普斯",
    "peach vodka": "桃味伏特加",
    "peachtree schnapps": "Peachtree 桃味施纳普斯",
    "pepper": "胡椒",
    "pepsi cola": "百事可乐",
    "pernod": "潘诺茴香酒",
    "peychaud bitters": "裴乔氏苦精",
    "pina colada mix": "椰林飘香预调液",
    "pineapple": "菠萝",
    "pineapple juice": "菠萝汁",
    "pineapple syrup": "菠萝糖浆",
    "pink lemonade": "粉红柠檬水",
    "pisang ambon": "Pisang Ambon 香蕉利口酒",
    "pisco": "皮斯科",
    "pomegranate juice": "石榴汁",
    "port": "波特酒",
    "powdered sugar": "糖粉",
    "prosecco": "普罗塞克起泡酒",
    "raspberry liqueur": "覆盆子利口酒",
    "raspberry syrup": "覆盆子糖浆",
    "raspberry vodka": "覆盆子伏特加",
    "red chili flakes": "红辣椒碎",
    "red wine": "红葡萄酒",
    "ricard": "力加茴香酒",
    "root beer": "沙士",
    "rose": "玫瑰",
    "rosemary": "迷迭香",
    "rosemary syrup": "迷迭香糖浆",
    "roses sweetened lime juice": "Rose's 青柠汁",
    "rosso vermouth": "红味美思",
    "ruby port": "红宝石波特酒",
    "rum": "朗姆酒",
    "rumple minze": "Rumple Minze 薄荷利口酒",
    "rye whiskey": "黑麦威士忌",
    "salt": "盐",
    "sambuca": "桑布卡茴香酒",
    "sarsaparilla": "菝葜汽水",
    "schweppes russchian": "怡泉 Russchian 汽水",
    "scotch": "苏格兰威士忌",
    "sherbet": "雪葩",
    "sherry": "雪莉酒",
    "sirup of roses": "玫瑰糖浆",
    "sloe gin": "黑刺李金酒",
    "soda water": "苏打水",
    "sour mix": "酸甜预调液",
    "southern comfort": "南方安逸利口酒",
    "soy sauce": "酱油",
    "spiced rum": "香料朗姆酒",
    "sprite": "雪碧",
    "st. germain": "圣哲曼接骨木花利口酒",
    "strawberries": "草莓",
    "strawberry liqueur": "草莓利口酒",
    "strawberry schnapps": "草莓施纳普斯",
    "sugar": "糖",
    "sugar syrup": "糖浆",
    "surge": "Surge 汽水",
    "sweet and sour": "酸甜预调液",
    "sweet vermouth": "甜味美思",
    "tabasco sauce": "塔巴斯科辣椒汁",
    "tea": "茶",
    "tennessee whiskey": "田纳西威士忌",
    "tequila": "龙舌兰酒",
    "thyme": "百里香",
    "tia maria": "添万利咖啡利口酒",
    "tomato juice": "番茄汁",
    "tonic water": "汤力水",
    "triple sec": "白橙皮利口酒",
    "vanilla": "香草",
    "vanilla extract": "香草精",
    "vanilla ice-cream": "香草冰淇淋",
    "vanilla syrup": "香草糖浆",
    "vanilla vodka": "香草伏特加",
    "vermouth": "味美思",
    "vodka": "伏特加",
    "water": "水",
    "whipped cream": "打发奶油",
    "whipping cream": "淡奶油",
    "whiskey": "威士忌",
    "whisky": "威士忌",
    "white creme de menthe": "白色薄荷利口酒",
    "white rum": "白朗姆酒",
    "white wine": "白葡萄酒",
    "wild turkey": "野火鸡波本威士忌",
    "wine": "葡萄酒",
    "worcestershire sauce": "伍斯特辣酱油",
    "wormwood": "苦艾草",
    "yellow chartreuse": "黄夏翠丝",
    "yoghurt": "酸奶",
    "yukon jack": "Yukon Jack 威士忌利口酒",
    "zima": "Zima 麦芽汽水",
  };

  const measures = [
    [/\bshots?\b/gi, "shot"],
    [/\bparts?\b/gi, "份"],
    [/\bcups?\b/gi, "杯"],
    [/\btblsp\b|\btbsp\b|\btablespoons?\b/gi, "汤匙"],
    [/\btsp\b|\bteaspoons?\b/gi, "茶匙"],
    [/\bslices?\b/gi, "片"],
    [/\bwedges?\b/gi, "角"],
    [/\bsprigs?\b/gi, "枝"],
    [/\bdashes?\b/gi, "dash"],
  ];

  function ingredient(name = "") {
    return ingredients[String(name).trim().toLocaleLowerCase()] || name;
  }

  function measure(value = "") {
    return measures.reduce((result, [pattern, replacement]) => result.replace(pattern, replacement), String(value).trim());
  }

  return { ingredient, measure };
})();
